# Generated by Django 3.2 on 2022-05-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resturant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmodule',
            name='total_save',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('total_like', models.IntegerField(default=0)),
                ('total_save', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_resturant.restaurantmodule')),
            ],
        ),
    ]
