# Generated by Django 3.2 on 2022-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resturant', '0002_auto_20220521_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='resturant', to='app_resturant.Restaurantmodule'),
        ),
    ]
